# Generated by Django 4.1 on 2024-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0002_alter_member_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职时间'),
        ),
    ]
