# Generated by Django 4.1 on 2024-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0005_admin_alter_prettynum_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '未使用'), (1, '已占用')], default=2, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=3, verbose_name='等级')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('details', models.CharField(max_length=64, verbose_name='详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.admin', verbose_name='负责人')),
            ],
        ),
    ]
