# Generated by Django 4.1 on 2024-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0006_alter_prettynum_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已占用'), (2, '未使用')], default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(max_length=64, verbose_name='详细信息'),
        ),
    ]
