# Generated by Django 4.1 on 2024-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0007_alter_prettynum_status_alter_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(verbose_name='详细信息'),
        ),
    ]
