# Generated by Django 4.1 on 2024-04-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0009_alter_prettynum_status_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='昵称')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('avatar', models.CharField(max_length=128, verbose_name='头像')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已占用'), (2, '未使用')], default=2, verbose_name='状态'),
        ),
    ]
